abbr = {'Alaska': 'AK',
       'Oregon': 'OR',
       'Mississippi': 'MS',
       'Montana': 'MT',
       'Utah': 'UT',
       'Ohio': 'OH',
       'Texas': 'TX',
       'Maine': 'ME',
       'Indiana': 'IN',
       'Guam': 'GU',
       'Maryland':'MD',
       'Arkansas': 'AR',
       'Minnesota': 'MN',
       'Kansas': 'KS',
       'Rhode Island': 'RI',
       'North Carolina': 'NC',
       'Delaware': 'DE',
       'Tennessee': 'TN',
       'Massachusetts': 'MA',
       'Iowa': 'IA',
       'Wisconsin': 'WI',
       'Arizona': 'AZ',
       'North Dakota': 'ND',
       'American Samoa': 'AS',
       'Nevada': 'NV',
       'California': 'CA',
       'Nebraska': 'NE',
       'New Jersey': 'NJ',
       'Connecticut': 'CT',
       'Virginia': 'VA',
       'Virgin Islands': 'VI',
       'Kentucky': 'KY',
       'Illinois': 'IL',
       'National': 'NA',
       'Louisiana': 'LA',
       'Pennsylvania': 'PA',
       'Oklahoma': 'OK',
       'Georgia': 'GA',
       'Puerto Rico': 'PR',
       'New Hampshire': 'NH',
       'Wyoming': 'WY',
       'Washington': 'WA',
       'Missouri': 'MO',
       'New Mexico': 'NM',
       'Florida': 'FL',
       'Alabama': 'AL',
       'South Dakota': 'SD',
       'New York': 'NY',
       'Northern Mariana Islands': 'MP',
       'District of Columbia': 'DC',
       'Hawaii': 'HI',
       'Michigan': 'MI',
       'South Carolina': 'SC',
       'Vermont': 'VT',
       'West Virginia': 'WV',
       'Idaho': 'ID',
       'Colorado': 'CO'}
